name: Deploy to Server

on:
  push:
    branches:
      - main  # Déclenche le workflow lorsqu'il y a un push sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Exécute le job sur une machine virtuelle Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known_hosts
        run: |
          ssh-keyscan hopeful117.duckdns.org >> ~/.ssh/known_hosts

      - name: Deploy using Git
        run: |
          ssh -o StrictHostKeyChecking=no ludo@hopeful117.duckdns.org << 'EOF'
            # Naviguer dans le dépôt sur le serveur
            cd /var/www/DLL/CS50_final
            # Récupérer les dernières modifications du dépôt GitHub
            git pull origin main
            # Assurez-vous que les permissions sont correctes si nécessaire
            chmod -R u+rwx /var/www/DLL/CS50_final
            # Mettre à jour l'environnement virtuel et installer les dépendances
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            # Redémarrer les services
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
          EOF
